### ISSUE TITLE
Cuadro comparativo 

### ISSUE THREAD

**Issue by 0eeixl** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-0eeixl#1]
[cuadro comparativvo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-0eeixl/files/9569623/cuadro.comparativvo.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica tiene un 17%

**Comment by josealfredo79** [comment]
y las referencias...

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by josealfredo79** [comment]
Calificacion de 15
